### ISSUE TITLE
Unable to run Minitube 3.0

### ISSUE THREAD

**Issue by ferlanero** [flaviotordini/minitube#125]
After susccesfully compilled and installed Minitube 3.0 in Manjaro, when I run it, Minitube starts but inmediatelly closes with this error:

```
[ferlanero@manjaro ~]$ minitube
[unknown] using qt5ct plugin
[unknown] D-Bus global menu: no
[unknown] QObject::connect(QWindow, SearchView): invalid null parameter
[unknown] custom style sheet is disabled
Violación de segmento (`core' generado)
```

Any ideas?

Note: Minitube 2.9. runs flawselly.

**Comment by pc-magas** [comment]
For better output in English try to ost the error output of one of these commands:

```
LANG=en_US.utf-8 minitube
LANG=C minitube
```

**Comment by ferlanero** [comment]
Sure. Here you are:

```
[ferlanero@manjaro ~]$ minitube
[unknown] using qt5ct plugin
[unknown] D-Bus global menu: no
[unknown] QObject::connect(QWindow, SearchView): invalid null parameter
[unknown] custom style sheet is disabled
Segmentation fault ('core' dumped)
```
Still no luck even upgrading the whole QT to 5.12.2 version

**Note:** I have observed that Minitube 3.0 force closes after first cursor prompt in the search box. I don't know if this can help.

**Comment by flaviotordini** [comment]
Try with gdb:

    gdb minitube
    run
    backtrace

and send the stacktrace.

**Comment by ferlanero** [comment]
Here you are the full gdb results. I hope it helps:

```
[ferlanero@manjaro ~]$ gdb minitube
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "i686-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from minitube...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/minitube 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x2c09fb40 (LWP 861)]
[unknown] using qt5ct plugin
[New Thread 0x2b6ffb40 (LWP 862)]
[unknown] D-Bus global menu: no
[unknown] QObject::connect(QWindow, SearchView): invalid null parameter
[unknown] custom style sheet is disabled
[New Thread 0x29e62b40 (LWP 864)]
[New Thread 0x29661b40 (LWP 865)]
[New Thread 0x28e60b40 (LWP 866)]

Thread 1 "minitube" received signal SIGSEGV, Segmentation fault.
0x37e92dae in mpv_render_context_free () from /usr/lib/libmpv.so.1
(gdb) backtrace
#0  0x37e92dae in mpv_render_context_free () from /usr/lib/libmpv.so.1
#1  0x37e93111 in mpv_render_context_create () from /usr/lib/libmpv.so.1
#2  0x0043f5a4 in ?? ()
#3  0x377a6ede in ?? () from /usr/lib/libQt5Widgets.so.5
#4  0x377a7da3 in QOpenGLWidget::event(QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#5  0x3773b8b9 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#6  0x37743a22 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#7  0x364b7725 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#8  0x3777214d in ?? () from /usr/lib/libQt5Widgets.so.5
#9  0x37783cbe in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) ()
   from /usr/lib/libQt5Widgets.so.5
#10 0x377848b3 in QWidget::setParent(QWidget*) ()
   from /usr/lib/libQt5Widgets.so.5
#11 0x3775c22c in QLayout::addChildWidget(QWidget*) ()
   from /usr/lib/libQt5Widgets.so.5
#12 0x3776305f in QStackedLayout::insertWidget(int, QWidget*) ()
   from /usr/lib/libQt5Widgets.so.5
#13 0x3776317b in QStackedLayout::addWidget(QWidget*) ()
   from /usr/lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--c
#14 0x0046820f in ?? ()
#15 0x0046597b in ?? ()
#16 0x004659f8 in ?? ()
#17 0x364efe51 in ?? () from /usr/lib/libQt5Core.so.5
#18 0x364e3f5e in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#19 0x3773b8b9 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x37743a22 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#21 0x364b7725 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#22 0x36510ac1 in QTimerInfoList::activateTimers() () from /usr/lib/libQt5Core.so.5
#23 0x36511519 in ?? () from /usr/lib/libQt5Core.so.5
#24 0x3299ba1e in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#25 0x3299dafa in ?? () from /usr/lib/libglib-2.0.so.0
#26 0x3299db46 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#27 0x3651194b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#28 0x364b61b6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#29 0x364bea7b in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#30 0x0041e9b2 in main ()
(gdb) 
```

**Comment by flaviotordini** [comment]
Thank you, great job. LibMPV is crashing while trying initialise its OpenGL rendering context. This is not strictly a Minitube bug. This is probably already fixed in MPV https://github.com/mpv-player/mpv/issues/6507
