### ISSUE TITLE
segfaults due to lazyInit

### ISSUE THREAD

**Issue by d42** [flaviotordini/minitube#159]
since `MainWindow.lazyInit` initializes `mediaView`, it is possible to click on recent channels before the QTimer fires and end up in a state where `mediaView.playlistView` is not yet initialized
```
=================================================================
==1907016==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x564318d9b1ac bp 0x7ffefa409390 sp 0x7ffefa409380 T0)
==1907016==The signal is caused by a READ memory access.
==1907016==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x564318d9b1ac in PlaylistModel::activeVideo() const src/playlistmodel.cpp:159
    #1 0x564318d4ce41 in MediaView::appear() src/mediaview.cpp:340
    #2 0x564318d247b9 in MainWindow::showView(View*, bool) src/mainwindow.cpp:1054
    #3 0x564318d266fe in MainWindow::showMedia(SearchParams*) src/mainwindow.cpp:1181
    #4 0x564318e61c8f in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) build/moc/moc_mainwindow.cpp:271
    #5 0x7f0442e0893f  (/usr/lib/libQt5Core.so.5+0x2e993f)
    #6 0x564318e65b96 in SearchView::search(SearchParams*) build/moc/moc_searchview.cpp:190
    #7 0x564318d85be6 in SearchView::watchKeywords(QString const&) src/searchview.cpp:434
    #8 0x564318d826ec in operator() src/searchview.cpp:311
    #9 0x564318d89bea in call /usr/include/qt/QtCore/qobjectdefs_impl.h:146
    #10 0x564318d8950a in call<QtPrivate::List<>, void> /usr/include/qt/QtCore/qobjectdefs_impl.h:256
    #11 0x564318d89239 in impl /usr/include/qt/QtCore/qobjectdefs_impl.h:443
    #12 0x7f0442e08905  (/usr/lib/libQt5Core.so.5+0x2e9905)
    #13 0x564318e724a6 in ClickableLabel::clicked() build/moc/moc_clickablelabel.cpp:142
    #14 0x564318e2c367 in ClickableLabel::mouseReleaseEvent(QMouseEvent*) src/clickablelabel.cpp:12
    #15 0x7f0443f8dc6d in QWidget::event(QEvent*) (/usr/lib/libQt5Widgets.so.5+0x19dc6d)
    #16 0x7f0444038f8e in QFrame::event(QEvent*) (/usr/lib/libQt5Widgets.so.5+0x248f8e)
    #17 0x7f0443f4c6f1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x15c6f1)
    #18 0x7f0443f53966 in QApplication::notify(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x163966)
    #19 0x7f0442dd1699 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/usr/lib/libQt5Core.so.5+0x2b2699)
    #20 0x7f0443f5284d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (/usr/lib/libQt5Widgets.so.5+0x16284d)
    #21 0x7f0443fa63a1  (/usr/lib/libQt5Widgets.so.5+0x1b63a1)
    #22 0x7f0443fa977e  (/usr/lib/libQt5Widgets.so.5+0x1b977e)
    #23 0x7f0443f4c6f1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/usr/lib/libQt5Widgets.so.5+0x15c6f1)
    #24 0x7f0442dd1699 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/usr/lib/libQt5Core.so.5+0x2b2699)
    #25 0x7f0443851f1b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (/usr/lib/libQt5Gui.so.5+0x13bf1b)
    #26 0x7f04438276eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/usr/lib/libQt5Gui.so.5+0x1116eb)
    #27 0x7f0433fcec8b  (/usr/lib/libQt5XcbQpa.so.5+0x5ec8b)
    #28 0x7f043f23243b in g_main_context_dispatch (/usr/lib/libglib-2.0.so.0+0x5243b)
    #29 0x7f043f27ffa8  (/usr/lib/libglib-2.0.so.0+0x9ffa8)
    #30 0x7f043f231220 in g_main_context_iteration (/usr/lib/libglib-2.0.so.0+0x51220)
    #31 0x7f0442e2a210 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/usr/lib/libQt5Core.so.5+0x30b210)
    #32 0x7f0442dd001b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (/usr/lib/libQt5Core.so.5+0x2b101b)
    #33 0x7f0442dd84a3 in QCoreApplication::exec() (/usr/lib/libQt5Core.so.5+0x2b94a3)
    #34 0x564318cbd9f2 in main src/main.cpp:148
    #35 0x7f0442599001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #36 0x564318c8d68d in _start (/home/d42/p/minitube/build/target/minitube+0x2ed68d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/playlistmodel.cpp:159 in PlaylistModel::activeVideo() const
==1907016==ABORTING
```

**Comment by flaviotordini** [comment]
True. You have to be quick to trigger it. Will lower the delay.

**Comment by d42** [comment]
what's the reason behind delaying it in the first place, if you don't mind me asking? :^)

**Comment by flaviotordini** [comment]
The reason is showing the window before the multimedia engine is initialized.
