### ISSUE TITLE
crash on librecomputer (libvdpau?)

### ISSUE THREAD

**Issue by marnanel** [flaviotordini/minitube#248]
When I run the version of minitube packaged in Debian 12.4 (bookworm) on a librecomputer board, it consistently segfaults. It works fine on my laptop. I'm trying to narrow the problem down.

I built 3.9.3 with debug symbols from source. Running it through gdb gives
```
Failed to open VDPAU backend libvdpau_meson.so: cannot open shared object file: No such file or directory

Thread 12 "mpv/mpv core" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xffffafffe440 (LWP 5982)]
0x0000fffff53229d8 in ?? () from /lib/aarch64-linux-gnu/libavcodec.so.59
(gdb) bt
#0  0x0000fffff53229d8 in  () at /lib/aarch64-linux-gnu/libavcodec.so.59
#1  0x0000fffff53234bc in  () at /lib/aarch64-linux-gnu/libavcodec.so.59
#2  0x0000fffff4e83b74 in  () at /lib/aarch64-linux-gnu/libavcodec.so.59
#3  0x0000fffff4e849ac in avcodec_receive_frame () at /lib/aarch64-linux-gnu/libavcodec.so.59
#4  0x0000fffff7dd7af4 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#5  0x0000fffff7d76c10 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#6  0x0000fffff7d7e734 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#7  0x0000fffff7d7e8f0 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#8  0x0000fffff7d7ed8c in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#9  0x0000fffff7dc46c4 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#10 0x0000fffff7dc01cc in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#11 0x0000fffff7dba0b0 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#12 0x0000fffff7dbaf1c in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#13 0x0000fffff7da3508 in  () at /lib/aarch64-linux-gnu/libmpv.so.2
#14 0x0000fffff5e9ee18 in start_thread (arg=0xffffffffe217) at ./nptl/pthread_create.c:442
#15 0x0000fffff5f07e9c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```

The last few `open`s before the crash, as seen by strace:
```
[pid  5373] openat(AT_FDCWD, "/etc/vdpau_wrapper.cfg", O_RDONLY) = 88
[pid  5373] openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/vdpau/libvdpau_meson.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  5373] openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 88
[pid  5373] openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libvdpau_meson.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  5373] openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libvdpau_meson.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  5373] openat(AT_FDCWD, "/lib/libvdpau_meson.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  5373] openat(AT_FDCWD, "/usr/lib/libvdpau_meson.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid  5373] write(2, "Failed to open VDPAU backend lib"..., 106Failed to open VDPAU backend libvdpau_meson.so: cannot open shared object file: No 
such file or directory
[pid  5373] openat(AT_FDCWD, "/dev", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 87
[pid  5373] openat(AT_FDCWD, "/dev/video0", O_RDWR|O_NONBLOCK) = 88
[pid  5373] openat(AT_FDCWD, "/dev/video0", O_RDWR|O_NONBLOCK) = 87
```

In `/etc/vdpau_wrapper.cfg`:
```
enable_flash_uv_swap=1
disable_flash_pq_bg_color=1
```

Running xorg version 2:21.1.7-3+deb12u5.

The kernel:
```
$ uname -a
Linux allypally 6.1.74-12781-g74961fb0a5d2 #1 SMP PREEMPT_DYNAMIC Wed Jan 24 02:05:32 EST 2024 aarch64 GNU/Linux
```

What should I try next?

**Comment by flaviotordini** [comment]
I honestly don't know. Minitube uses libmpv. Try using MPV and see if you can recreate the problem. If yes, report it to the MPV devs.
